theme = "hugo-theme-slim"
baseURL = "https://slimdemo.netlify.com/"
languageCode = "en-us"
title = "Slim Theme Demo"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[Params]
  math = false
  summary = true
  disqusShortname = "slim-theme-demo"
  
  # social
  GithubID = "homerhanumat"
  TwitterID = "homerhanumat"
  LinkedInID = "homerwhite"
  
[[menu.main]]
  name = "About"
  URL = "/about/"